

export const lang = [
    {
        'SETTING': '设置',
        'APPLICATION': '应用库',
        'MARKDOWNEDITOR-DEFAULT': '**提示：**点击左边导航选择阅读',
        'BACKGROUND-AUTO-SWITCH': '背景自动切换',
        'BACKGROUND-SWITCH': '背景切换',
        'BACKGROUND-IMAGE-SETTING': '背景图片设置',
        'BACKGROUND-COLOR-SETTING': '背景颜色设置',
        'BACKGROUND-COLOR': '背景色',
        'BACKGROUND-FONT-COLOR': '背景字体色',
        'BACKGROUND-OPACITY': '透明度',
        'BAIDUMAP': '百度地图',
        'MYBLOB': '我的博客',
        'MRUI': 'MR UI',
        'ARTICLE': '文章',
        'LANGUAGE-SETTING': '语言设置',
        'LANGUAGE-SWITCH': '语言切换',
        'ENGLISH': '英文',
        'CHINESE': '中文',
        'WELCOME-MESSAGE': 'The Best',
        'WELCOME-DESC': '一直在等你。',
        'VIDEOPLAYER': '视频播放器',
    },
    {
        'SETTING': 'Setting',
        'APPLICATION': 'Application',
        'MARKDOWNEDITOR-DEFAULT': '**Notice: click navigation from left to select one article**',
        'BACKGROUND-AUTO-SWITCH': 'Background Auto Switch',
        'BACKGROUND-SWITCH': 'Background Switch',
        'BACKGROUND-IMAGE-SETTING': 'Background Image Setting',
        'BACKGROUND-COLOR-SETTING': 'Background Color Setting',
        'BACKGROUND-COLOR': 'Background Color',
        'BACKGROUND-FONT-COLOR': 'Background Font Color',
        'BACKGROUND-OPACITY': 'Opacity',
        'BAIDUMAP': 'Bai Du Map',
        'MYBLOB': 'My Blog',
        'MRUI': 'MR UI',
        'ARTICLE': 'Article',
        'LANGUAGE-SETTING': 'Language Setting',
        'LANGUAGE-SWITCH': 'Language Switch',
        'ENGLISH': 'English',
        'CHINESE': 'Chinese',
        'WELCOME-MESSAGE': 'The Best',
        'WELCOME-DESC': 'Always waiting for you.',
        'VIDEOPLAYER': 'Video Player'
    }
]

