

export const lang = [
    {
        'SETTING': '设置',
        'APPLICATION': '应用库',
        'MARKDOWNEDITOR-DEFAULT': '**提示：**点击左边导航选择阅读',
        'BACKGROUND-AUTO-SWITCH': '浏览照片',
        'BACKGROUND-SWITCH': '开启浏览照片',
        'BACKGROUND-IMAGE-SETTING': '背景图片设置',
        'BACKGROUND-COLOR-SETTING': '背景颜色设置',
        'BACKGROUND-COLOR': '背景色',
        'BACKGROUND-FONT-COLOR': '背景字体色',
        'BACKGROUND-OPACITY': '透明度',
        'LEAFLETMAP': '地图',
        'MYBLOB': '我的博客',
        'MRUI': 'MR UI',
        'ARTICLE': '文章',
        'LANGUAGE-SETTING': '语言设置',
        'LANGUAGE-SWITCH': '语言切换',
        'ENGLISH': '英文',
        'CHINESE': '中文',
        'WELCOME-MESSAGE': 'The Best',
        'WELCOME-DESC': '一直在等你。',
        'VIDEOPLAYER': '视频播放器',
        'SHOW-BACKGROUND-IMAGE': '显示背景图片',
        'SHOW-HEART': '显示红心',
        'MUSICPLAYER': '音乐播放器'
    },
    {
        'SETTING': 'Setting',
        'APPLICATION': 'Application',
        'MARKDOWNEDITOR-DEFAULT': '**Notice: click navigation from left to select one article**',
        'BACKGROUND-AUTO-SWITCH': 'Display Photo',
        'BACKGROUND-SWITCH': 'Start Display Photo',
        'BACKGROUND-IMAGE-SETTING': 'Background Image Setting',
        'BACKGROUND-COLOR-SETTING': 'Background Color Setting',
        'BACKGROUND-COLOR': 'Background Color',
        'BACKGROUND-FONT-COLOR': 'Background Font Color',
        'BACKGROUND-OPACITY': 'Opacity',
        'LEAFLETMAP': 'Map',
        'MYBLOB': 'My Blog',
        'MRUI': 'MR UI',
        'ARTICLE': 'Article',
        'LANGUAGE-SETTING': 'Language Setting',
        'LANGUAGE-SWITCH': 'Language Switch',
        'ENGLISH': 'English',
        'CHINESE': 'Chinese',
        'WELCOME-MESSAGE': 'The Best',
        'WELCOME-DESC': 'Always waiting for you.',
        'VIDEOPLAYER': 'Video Player',
        'SHOW-BACKGROUND-IMAGE': "Background Image",
        'SHOW-HEART': 'Show Red Heart',
        'MUSICPLAYER': 'Music Player'
    }
]

